Repository Kernel360/F2-BIENGUAL-FE, pull requests merged in 2024-10, with the labels that each got.

#27 feat : rewrites Rule을 이용하여 proxy 서버 세팅
  next.config.mjs
Labels: ✨ feat

#33 feat : login버튼 누르면 oauth와 연결되는 로직 작성. 그러나 Oauth로그인은 아직 안 됨.
  next.config.mjs
  src/app/login/page.tsx
Labels: ✨ feat

#31 feat : 레이아웃 컴포넌트의 최대 너비 설정 및 스타일 수정
  next.config.mjs
  src/app/globals.css
  src/app/learn/listening/page.tsx
  src/app/learn/page.tsx
  src/app/learn/reading/page.tsx
  src/app/mypage/challenges/page.tsx
  src/components/ContentsCard.tsx
  src/components/Header.tsx
  src/mock/cardData.json
  src/mock/listeningList.json
  src/mock/readingList.json
  tailwind.config.ts
Labels: 🌈design

#34 feat: 로그인 쿠키 확인 테스트용 커밋
  src/app/test/page.tsx
Labels: ✨ feat

#35 fix: 배포 로그인 테스트를 위한 도메인 주소 변경
  next.config.mjs
  src/app/login/page.tsx
Labels: 🐞 fix

#36 fix : 도메인 주소 오타 수정
  next.config.mjs
Labels: 🐞 fix

#37 feat : 인기 리딩, 리스닝 콘텐츠 보여주는 캐러셀 컴포넌트 구현
  .eslintrc.json
  package-lock.json
  package.json
  src/app/page.tsx
  src/components/Carousel.tsx
  src/components/ListeningPreviewCard.tsx
  src/components/ReadingPreviewCard.tsx
  src/components/ui/carousel.tsx
  src/mock/readingList.json
  src/types/index.ts
Labels: ✨ feat, ⚒️ refactor

#38 feat : 리딩 디테일 페이지 기본 레이아웃 구현,
  package-lock.json
  package.json
  src/app/learn/reading/detail/[id]/page.tsx
  src/components/ReadingPreview.tsx
  src/components/ui/separator.tsx
  src/mock/readingDetailData.json
Labels: ✨ feat, 🌈design

#42 feat: 문장 순서 맞추기 퀴즈 컴포넌트, 퀴즈 캐러셀 구현
  .eslintrc.json
  src/app/learn/reading/detail/[id]/page.tsx
  src/app/page.tsx
  src/components/Carousel.tsx
  src/components/quiz/Quiz.tsx
  src/components/quiz/QuizCarousel.tsx
  src/mock/quizData.json
Labels: 🌝 fe, ✨ feat

#43 design : 북마크사이드바 컴포넌트 디자인 develop
  src/app/learn/reading/detail/[id]/page.tsx
  src/components/BookmarkSidebar.tsx
  src/components/ResponsiveSidebar.tsx
  src/components/ui/button.tsx
Labels: 🌈design

#45 feat : 퀴즈 제출 시 자동으로 다음 퀴즈로 넘어가는 기능 추가 및 정답/오답 여부 표시
  src/components/Carousel.tsx
  src/components/quiz/Quiz.tsx
  src/lib/utils.ts
Labels: 🌝 fe, ✨ feat

#47 feat : tanstack query 초기 설정
  .gitignore
  package.json
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/test/page.tsx
  src/providers/Providers.tsx
Labels: ✨ feat, ⚙️ chore

#50 design : 색상, 폰트 변경
  src/app/fonts/GeistMonoVF.woff
  src/app/fonts/GeistVF.woff
  src/app/globals.css
  src/app/layout.tsx
  src/app/learn/reading/detail/[id]/page.tsx
  src/app/page.tsx
  src/components/Carousel.tsx
  src/components/Header.tsx
  src/components/ListeningPreviewCard.tsx
  src/components/ReadingPreviewCard.tsx
  tailwind.config.ts
Labels: 🌝 fe, 🌈design

#51 feat : 북마크 하이라이트 및 메모 기능 구현 및 모달 컴포넌트 구현
  src/app/learn/reading/detail/[id]/page.tsx
  src/components/MemoInput.tsx
  src/components/Modal.tsx
  src/components/Tooltip.tsx
Labels: 🌝 fe, ✨ feat, 🌈design

#56 feat : 라이브러리 레포의 demo폴더를 애플리케이션 videoPlayer폴더로 코드만 복사
  package-lock.json
  package.json
  src/app/learn/listening/detail/[id]/page.tsx
  src/app/learn/listening/page.tsx
  src/components/BookmarkSidebar.tsx
  src/components/VideoPlayer/ControlBar.tsx
  src/components/VideoPlayer/SubtitleOption.module.scss
  src/components/VideoPlayer/SubtitleOption.tsx
  src/components/VideoPlayer/VideoPlayer.module.scss
  src/components/VideoPlayer/core/ReactScriptPlayer/BlockView.tsx
  src/components/VideoPlayer/core/ReactScriptPlayer/Button.tsx
  src/components/VideoPlayer/core/ReactScriptPlayer/LineView.tsx
  src/components/VideoPlayer/core/ReactScriptPlayer/ReactScriptPlayer.module.scss
  src/components/VideoPlayer/core/ReactScriptPlayer/TextDisplay.tsx
  src/components/VideoPlayer/core/ReactScriptPlayer/index.tsx
  src/components/VideoPlayer/core/assets/icons/arrow_back.svg
  src/components/VideoPlayer/core/assets/icons/arrow_forward.svg
  src/components/VideoPlayer/core/interfaces/Scripts.ts
  src/components/VideoPlayer/core/utils/convertTime.ts
  src/components/VideoPlayer/index.tsx
  src/components/VideoPlayer/mocks/mockUrl.ts
  src/components/VideoPlayer/mocks/subtitleMockData.ts
  src/components/VideoPlayer/utils/formatTime.ts
Labels: ✨ feat

#53 feat : 스크랩북 페이지 구현
  src/app/learn/reading/page.tsx
  src/app/scrapbook/content/page.tsx
  src/app/scrapbook/highlight/page.tsx
  src/app/scrapbook/layout.tsx
  src/components/ArticlePreview.tsx
  src/components/Header.tsx
  src/components/MemoItem.tsx
  src/components/ReadingPreview.tsx
Labels: 🌝 fe, ✨ feat

#61 refactor : 라이브러리 컴포넌트 폴더 구조 수정 및 scss를 tailwind css로 변경
  package-lock.json
  package.json
  src/app/learn/listening/detail/[id]/page.tsx
  src/components/ControlBar.tsx
  src/components/ReactScriptPlayer/BlockView.tsx
  src/components/ReactScriptPlayer/Button.tsx
  src/components/ReactScriptPlayer/LineView.tsx
  src/components/ReactScriptPlayer/TextDisplay.tsx
  src/components/ReactScriptPlayer/index.tsx
  src/components/SubtitleOption.tsx
  src/components/VideoPlayer.tsx
  src/components/VideoPlayer/SubtitleOption.module.scss
  src/components/VideoPlayer/VideoPlayer.module.scss
  src/components/VideoPlayer/core/ReactScriptPlayer/ReactScriptPlayer.module.scss
  src/components/VideoPlayer/core/assets/icons/arrow_back.svg
  src/components/VideoPlayer/core/assets/icons/arrow_forward.svg
  src/lib/convertTime.ts
  src/lib/formatTime.ts
  src/mock/mockUrl.ts
  src/mock/subtitleMockData.ts
  src/types/Scripts.ts
Labels: 🌝 fe, 🐞 fix, ⚒️ refactor

#59 feat : 마이페이지/프로필 UI 만들기
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/app/mypage/profile/page.tsx
  src/components/Header.tsx
Labels: ✨ feat, 🌈design

#66 feat : 리딩 콘텐츠, 북마크 쿼리 함수 분리 및 커스텀 쿼리 구현
  .gitignore
  src/api/hooks/useBookmarks.ts
  src/api/hooks/useContentDetail.ts
  src/api/queries/bookmarkQuries.ts
  src/api/queries/contentsQueries.ts
  src/app/learn/reading/detail/[id]/page.tsx
  src/components/Tooltip.tsx
  src/types/Bookmark.ts
  src/types/ContentDetail.ts
Labels: 🌝 fe, ✨ feat

#69 feat : connect mypage api
  src/api/hooks/useBookmarks.ts
  src/api/hooks/useUserInfo.ts
  src/api/queries/bookmarkQueries.ts
  src/api/queries/userQueries.ts
  src/app/mypage/profile/page.tsx
  src/types/User.ts
Labels: ✨ feat

#72 feat : 운영, 개발 서버에 따라 api 요청 baseUrl 변경할 수 있도록 수정
  src/api/hooks/useUserInfo.ts
  src/api/queries/bookmarkQueries.ts
  src/api/queries/contentsQueries.ts
  src/api/queries/userQueries.ts
  src/app/login/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/test/page.tsx
Labels: ✨ feat, ⚙️ chore

#74 [fix] nextjs Image태그를 일반 img태그로 변경
  next.config.mjs
  src/app/learn/reading/detail/[id]/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/scrapbook/highlight/page.tsx
  src/components/ArticlePreview.tsx
  src/components/ContentsCard.tsx
  src/components/ListeningPreviewCard.tsx
Labels: 🐞 fix

#79 fix : next 처음 로드 시 .next에 layout.js 파일 생성 안되는 문제 및 css 안 입혀지는 문제 해결
  next.config.mjs
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/learn/listening/page.tsx
  src/app/learn/reading/detail/[id]/page.tsx
  src/app/page.tsx
  src/components/ArticlePreview.tsx
  src/components/ListeningPreviewCard.tsx
  src/components/ReadingPreviewCard.tsx
  src/lib/removeFirstChar.ts
  src/mock/listeningList.json
  src/providers/Providers.tsx
  src/types/Preview.ts
Labels: 🌝 fe, 🐞 fix

#82 feat : 학습 페이지 UI 구현 및 api 연결
  src/api/hooks/usePreview.ts
  src/api/queries/contentsQueries.ts
  src/app/learn/layout.tsx
  src/app/learn/listening/page.tsx
  src/app/learn/page.tsx
  src/app/learn/reading/page.tsx
  src/app/page.tsx
  src/app/scrapbook/content/page.tsx
  src/components/ArticlePreview.tsx
  src/components/Carousel.tsx
  src/components/Header.tsx
  src/components/ListeningPreviewCard.tsx
  src/components/ReadingPreviewCard.tsx
  src/types/Preview.ts
Labels: 🌝 fe, ✨ feat

#83 feat : 스크랩 페이지의 북마크 수정, 삭제, 전체 불러오기 기능 구현
  src/api/hooks/useBookmarks.ts
  src/api/hooks/usePreview.ts
  src/api/hooks/useScrap.ts
  src/api/queries/bookmarkQueries.ts
  src/api/queries/contentsQueries.ts
  src/api/queries/scrapQueries.ts
  src/app/learn/reading/detail/[id]/page.tsx
  src/app/page.tsx
  src/app/scrapbook/highlight/page.tsx
  src/components/MemoItem.tsx
  src/lib/convertTimestampToDate.ts
  src/types/Bookmark.ts
  src/types/Preview.ts
  src/types/Scrap.ts
Labels: 🌝 fe, ✨ feat, 🐞 fix

#85 리스닝디테일 페이지 develop
  package.json
  src/app/learn/listening/detail/[id]/page.tsx
  src/components/ControlBar.tsx
  src/components/ReactScriptPlayer/BlockView.tsx
  src/components/ReactScriptPlayer/LineView.tsx
  src/components/ReactScriptPlayer/TextDisplay.tsx
  src/components/ReactScriptPlayer/index.tsx
  src/components/SubtitleOption.tsx
  src/components/VideoPlayer.tsx
  src/components/ui/toggle-group.tsx
  src/components/ui/toggle.tsx
  src/mock/subtitleMockData.ts
  src/types/Scripts.ts
  tailwind.config.ts
Labels: ✨ feat, 🌈design

#87 feat : 스크랩 콘텐츠 보여주는 페이지 및 스크랩 플로팅 버튼 구현
  package-lock.json
  src/api/hooks/useScrap.ts
  src/api/queries/scrapQueries.ts
  src/app/learn/layout.tsx
  src/app/learn/listening/page.tsx
  src/app/learn/reading/detail/[id]/page.tsx
  src/app/learn/reading/page.tsx
  src/app/scrapbook/content/page.tsx
  src/components/ArticlePreview.tsx
  src/components/ContentTypeFilter.tsx
  src/components/FloatingButtons.tsx
  src/components/MemoItem.tsx
  src/lib/convertTimestampToDate.ts
  src/lib/formatDate.ts
  src/types/Scrap.ts
Labels: 🌝 fe, ✨ feat

#89 chore : bookmark 사용 로직 훅으로 분리
  src/hooks/useBookmarkManager.ts
Labels: ⚙️ chore

#96 feat : 리스닝 페이지 북마크 api 연결, 재배치
  src/app/learn/listening/detail/[id]/page.tsx
  src/components/BookmarkMemoItem.tsx
  src/components/ControlBar.tsx
  src/components/ReactScriptPlayer/BlockView.tsx
  src/components/ReactScriptPlayer/LineView.tsx
  src/components/ReactScriptPlayer/index.tsx
  src/components/SubtitleOption.tsx
  src/components/VideoPlayer.tsx
  src/components/ui/textarea.tsx
  src/types/ContentDetail.ts
Labels: 🌝 fe, ✨ feat, 🌈design

#99 design : pretendard 폰트 다운로드 및 적용
  next.config.mjs
  src/app/fonts/PretendardVariable.woff2
  src/app/globals.css
  src/app/layout.tsx
  src/app/learn/reading/detail/[id]/page.tsx
  src/components/ArticlePreview.tsx
  src/components/ListeningPreviewCard.tsx
  src/components/ReadingPreviewCard.tsx
  src/lib/removeFirstChar.ts
Labels: 🌝 fe, 🌈design

#98 design : 사이드영역에 들어갈 학습트래커 컴포넌트 ui 구현, 컨텐츠 들어갈 기본 레이아웃컴포넌트 구현
  package-lock.json
  package.json
  src/api/hooks/useUserInfo.ts
  src/api/queries/userQueries.ts
  src/app/layout.tsx
  src/app/learn/listening/detail/[id]/page.tsx
  src/app/learn/reading/detail/[id]/page.tsx
  src/app/page.tsx
  src/components/layout/ContentInner.tsx
  src/components/layout/Header.tsx
  src/components/layout/MobileNav.tsx
  src/components/layout/SideArea.tsx
  src/components/side/BookmarkSidebar.tsx
  src/components/side/LearningTracker.tsx
  src/components/ui/progress.tsx
  src/components/ui/scroll-area.tsx
  src/components/ui/tabs.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toggle-group.tsx
  src/lib/calculateDaysBetweenDates.ts
  src/types/User.ts
Labels: 🌈design

#104 fix : layout 에러 수정
  src/app/learn/reading/detail/[id]/page.tsx
Labels: 🐞 fix

#105 feat : 스크랩 콘텐츠 타입에 따라 배지로 구분
  next.config.mjs
  src/app/learn/listening/detail/[id]/page.tsx
  src/app/scrapbook/content/page.tsx
  src/components/ContentPreview.tsx
  src/components/FloatingButtons.tsx
Labels: 🌝 fe, ✨ feat, 🌈design

#106 feat : 로그인 여부에 따라 로그인,로그아웃 버튼 보여주기
  src/api/hooks/useUserInfo.ts
  src/api/queries/userQueries.ts
  src/app/layout.tsx
  src/components/LogInOutButton.tsx
  src/components/layout/Header.tsx
  src/providers/QueryClientProvider.tsx
  src/types/User.ts
Labels: ✨ feat

#108 design : 전체적인 layout 넓이 패딩 수정
  src/app/layout.tsx
  src/app/learn/layout.tsx
  src/app/learn/listening/detail/[id]/page.tsx
  src/app/learn/listening/page.tsx
  src/app/learn/reading/detail/[id]/page.tsx
  src/app/learn/reading/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/scrapbook/content/page.tsx
  src/app/scrapbook/highlight/page.tsx
  src/app/scrapbook/layout.tsx
  src/app/test/page.tsx
  src/components/ArticlePreview.tsx
  src/components/Carousel.tsx
  src/components/FloatingButtons.tsx
  src/components/MemoItem.tsx
  src/components/VideoPlayer.tsx
  src/components/layout/ContentWrapper.tsx
  src/components/layout/SideArea.tsx
  src/components/side/LearningTracker.tsx
Labels: 🌝 fe, ✨ feat, 🌈design

#111 feat : login이 안 되어있으면 login페이지로 이동, 툴팁 띄우기
  src/app/learn/listening/detail/[id]/page.tsx
  src/app/learn/reading/detail/[id]/page.tsx
  src/app/scrapbook/layout.tsx
  src/components/DisabledModal.tsx
  src/components/Tooltip.tsx
  src/components/VideoPlayer.tsx
  src/middleware.ts
Labels: ✨ feat, 🌈design

#114 feat : 영상과 자막, 북마크의 싱크 더 자세히 맞추는 함수 구현
  src/components/BookmarkMemoItem.tsx
  src/components/ReactScriptPlayer/LineView.tsx
  src/components/ReactScriptPlayer/index.tsx
  src/components/VideoPlayer.tsx
  src/lib/findCurrentSubtitleIndex.ts
Labels: 🌝 fe, ✨ feat, 🐞 fix

#115 feat : 캐러셀 컴포넌트 크기 수정
  src/app/page.tsx
  src/components/Carousel.tsx
  src/components/ListeningPreviewCard.tsx
  src/components/ReadingPreviewCard.tsx
  src/components/quiz/BlankQuiz.tsx
  src/components/quiz/OrderQuiz.tsx
  src/components/quiz/Quiz.tsx
  src/components/quiz/QuizCarousel.tsx
Labels: 🌝 fe, ✨ feat, 🌈design

#121 feat : group routing위해 폴더구조 변경
  src/app/(default)/layout.tsx
  src/app/(default)/learn/layout.tsx
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/app/(default)/learn/listening/page.tsx
  src/app/(default)/learn/reading/detail/[id]/page.tsx
  src/app/(default)/learn/reading/page.tsx
  src/app/(default)/mypage/layout.tsx
  src/app/(default)/mypage/learn/page.tsx
  src/app/(default)/mypage/profile/page.tsx
  src/app/(default)/page.tsx
  src/app/(default)/scrapbook/content/page.tsx
  src/app/(default)/scrapbook/highlight/page.tsx
  src/app/(default)/scrapbook/layout.tsx
  src/app/(default)/search/page.tsx
  src/app/(fullscreen)/layout.tsx
  src/app/(fullscreen)/login/page.tsx
  src/components/layout/ContentWrapper.tsx
Labels: 🌝 fe, ✨ feat, ⚒️ refactor

#120 feat : design listening detail memo input
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/app/(default)/page.tsx
  src/components/BookmarkMemoItem.tsx
  src/components/ListeningPreviewCard.tsx
  src/components/MemoItem.tsx
  src/components/ReactScriptPlayer/TextDisplay.tsx
  src/components/SubtitleOption.tsx
  src/components/VideoPlayer.tsx
  src/types/Bookmark.ts
Labels: 🌝 fe, ✨ feat, 🌈design

#126 fix: useSearchParams 사용하는 곳을 suspense로 감싸줌
  src/app/(default)/search/page.tsx
  src/app/(fullscreen)/login/page.tsx
Labels: 🌝 fe, 🐞 fix

#127 [feat] 검색 컴포넌트와 기본적인 검색 기능 구현
  src/api/hooks/useSearch.ts
  src/api/queries/searchQuries.ts
  src/app/(default)/search/page.tsx
  src/app/(fullscreen)/login/page.tsx
  src/components/SearchComponent.tsx
  src/components/layout/Header.tsx
  src/types/Preview.ts
  src/types/Search.ts
Labels: 🌝 fe, ✨ feat, 🐞 fix

#131 [feat] 마이페이지 디벨롭
  src/app/(default)/mypage/layout.tsx
  src/app/(default)/mypage/profile/page.tsx
  src/app/(fullscreen)/login/page.tsx
Labels: ✨ feat, 🌈design

#133 feat : 로그인 여부에 따라 useQuery api 요청 활성화
  src/api/hooks/common.ts
  src/api/hooks/useBookmarks.ts
  src/api/hooks/useQuiz.ts
  src/api/hooks/useScrap.ts
  src/api/hooks/useUserInfo.ts
  src/api/hooks/useUserLoginStatus.ts
  src/app/(default)/layout.tsx
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/app/(default)/learn/reading/detail/[id]/page.tsx
  src/app/(default)/scrapbook/layout.tsx
  src/components/BookmarkMemoItem.tsx
  src/components/ListeningPreviewCard.tsx
  src/components/LogInOutButton.tsx
  src/components/Tooltip.tsx
  src/components/VideoPlayer.tsx
  src/components/quiz/Quiz.tsx
  src/components/ui/badge.tsx
Labels: 🌝 fe, ✨ feat, 🐞 fix

#135 fix: useUserLoginStatus import 경로 수정
  src/app/(default)/mypage/layout.tsx
Labels: 🌝 fe, 🐞 fix

#136 [feat] 검색 컴포넌트 디자인 변경, 개행문자 미포함 로직 추가
  src/components/SearchComponent.tsx
  src/components/layout/Header.tsx
Labels: ✨ feat, 🌈design

#137 발표전 미세한 디자인,기능 이슈 수정
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/app/(default)/learn/listening/page.tsx
  src/app/(default)/learn/reading/detail/[id]/page.tsx
  src/app/(default)/learn/reading/page.tsx
  src/app/(default)/mypage/profile/page.tsx
  src/app/(default)/page.tsx
  src/app/(default)/scrapbook/content/page.tsx
  src/app/(default)/scrapbook/highlight/page.tsx
  src/app/(default)/search/page.tsx
  src/app/(fullscreen)/login/page.tsx
  src/components/EmptyAlert.tsx
  src/components/LoadingSpinner.tsx
  src/components/LogInOutButton.tsx
  src/components/MemoItem.tsx
  src/components/ScrollProgressBar.tsx
  src/components/VideoPlayer.tsx
  src/components/layout/ContentWrapper.tsx
  src/components/quiz/QuizCover.tsx
  src/components/ui/alert.tsx
Labels: 🐞 fix, 🌈design

#138 북마크, 메모 버튼 누르면 토스트 알림, 버튼에 throttling 걸기
  package-lock.json
  package.json
  src/app/(default)/layout.tsx
  src/components/ReactScriptPlayer/LineView.tsx
  src/components/VideoPlayer.tsx
  src/components/ui/alert.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/hooks/use-toast.ts
  src/lib/useThrottling.ts
Labels: ✨ feat

#140 Update README.md
  README.md
Labels: 📑 docs

#142 feat : 마이페이지 로그인 상태가 유지가 안 되는 문제 해결
  src/api/hooks/useUserLoginStatus.ts
  src/app/(default)/layout.tsx
  src/providers/QueryClientProvider.tsx
Labels: ✨ feat

#146 feat : 페이지네이션 컴포넌트 구현
  src/api/hooks/usePreview.ts
  src/api/queries/contentsQueries.ts
  src/app/(default)/learn/listening/page.tsx
  src/app/(default)/learn/reading/page.tsx
  src/components/Pagination.tsx
Labels: 🌝 fe, ✨ feat

#147 feat : 영상컨텐츠추가 admin페이지 구현
  src/app/(fullscreen)/admin/create/page.tsx
  src/app/(fullscreen)/admin/layout.tsx
  src/types/CreateContents.ts
Labels: ✨ feat

#154 docs : 카테고리 로직 구현 함수 todo로 작성
  src/app/(default)/mypage/profile/page.tsx
  src/app/(fullscreen)/login/add/page.tsx
Labels: 📑 docs, 🌈design

#156 refactor : forwardRef를 사용해서 videoPlayer의 reactplayer 분리 및 북마크 메모 리팩토링
  .eslintrc.json
  src/api/hooks/useBookmarks.ts
  src/api/hooks/useScrap.ts
  src/app/(default)/layout.tsx
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/app/(default)/learn/reading/detail/[id]/page.tsx
  src/app/(default)/mypage/layout.tsx
  src/app/(default)/mypage/profile/page.tsx
  src/app/(default)/page.tsx
  src/app/(default)/scrapbook/layout.tsx
  src/app/(default)/search/page.tsx
  src/app/(fullscreen)/admin/layout.tsx
  src/app/(fullscreen)/login/page.tsx
  src/components/BookmarkMemoItem.tsx
  src/components/BookmarkMemoPanel.tsx
  src/components/Button/Button.stories.tsx
  src/components/Carousel.tsx
  src/components/ContentPreview.tsx
  src/components/ControlBar.tsx
  src/components/Input/Input.stories.tsx
  src/components/ListeningMemoForm.tsx
  src/components/ListeningPreviewCard.tsx
  src/components/MemoInput.tsx
  src/components/MemoItem.tsx
  src/components/Pagination.tsx
  src/components/ReactScriptPlayer/BlockView.tsx
  src/components/ReactScriptPlayer/LineView.tsx
  src/components/ReactScriptPlayer/index.tsx
  src/components/ReadingPreviewCard.tsx
  src/components/ReadingScriptItem.tsx
  src/components/SearchComponent.tsx
  src/components/SubtitleOption.tsx
  src/components/Tooltip.tsx
  src/components/VideoPlayer.tsx
  src/components/layout/ContentWrapper.tsx
  src/components/layout/Header.tsx
  src/components/layout/SideArea.tsx
  src/components/quiz/Quiz.tsx
  src/components/quiz/QuizCarousel.tsx
  src/components/side/BookmarkSidebar.tsx
  src/hooks/useBookmarkManager.ts
  src/hooks/useHandleBookmark.ts
  src/middleware.ts
  src/stories/Button.stories.ts
Labels: 🌝 fe, ✨ feat

#157 [feat] admin page initialData로 api로 data가져온 거 빠르게 보여주기
  src/api/hooks/usePreview.ts
  src/api/hooks/useUserLoginStatus.ts
  src/api/queries/contentsQueries.ts
  src/app/(default)/learn/reading/page.tsx
  src/app/(fullscreen)/admin/create/listening/page.tsx
  src/app/(fullscreen)/admin/layout.tsx
  src/app/(fullscreen)/admin/list/ListTable.tsx
  src/app/(fullscreen)/admin/list/reading/page.tsx
  src/app/(fullscreen)/layout.tsx
  src/providers/QueryClientProvider.tsx
Labels: ✨ feat

#162 refactor : 여러개로 혼재되어있던 preview 컴포넌트를 ContentCard, ListItem컴포넌트로 추상화
  src/api/queries/scrapQueries.ts
  src/app/(default)/learn/listening/page.tsx
  src/app/(default)/learn/reading/page.tsx
  src/app/(default)/page.tsx
  src/app/(default)/search/page.tsx
  src/components/common/ArticlePreview.tsx
  src/components/items/ContentCard.tsx
  src/components/items/ListItem.tsx
  src/components/listening/ListeningPreviewCard.tsx
Labels: ⚒️ refactor

#167 fix : quiz 타입 수정
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/app/(default)/learn/reading/detail/[id]/page.tsx
  src/types/Quiz.ts
Labels: 🌝 fe, 🐞 fix

#168 feat : 프리뷰컴포넌트에 북마크 기능 붙이기
  src/app/(default)/learn/listening/page.tsx
  src/app/(default)/page.tsx
  src/app/(default)/scrapbook/content/page.tsx
  src/app/(default)/search/page.tsx
  src/components/PreviewScrapButton.tsx
  src/components/common/FloatingButtons.tsx
  src/components/items/ContentCard.tsx
  src/hooks/useHandleScrap.ts
Labels: ✨ feat, ⚙️ chore

#169 feat: 서버 사이드에서 초기 리딩/리스닝 콘텐츠 목록을 가져오고 useQuery에서 initialData로 사용
  src/api/hooks/useScrap.ts
  src/app/(default)/page.tsx
  src/components/HomePageClient.tsx
  src/components/ItemComponent.tsx
Labels: 🌝 fe, ✨ feat, 🐞 fix

#173 feat : 포인트 내역 페이지 구현
  package-lock.json
  package.json
  src/app/(default)/point/page.tsx
  src/components/ui/accordion.tsx
  src/lib/formDateToMonthDay.ts
  src/mock/pointsHistory.json
  tailwind.config.ts
Labels: 🌝 fe, ✨ feat

#172 feat : 변경된 paginated api 에 맞춰 parameter 값 조정
  src/api/hooks/usePreview.ts
  src/api/queries/contentsQueries.ts
  src/app/(default)/learn/listening/page.tsx
  src/app/(default)/learn/reading/page.tsx
Labels: ✨ feat

#174 fix: next image태그에 따른 에러 해결, next/Image 에러 해결
  src/components/items/ContentCard.tsx
  src/components/layout/side/LearningTracker.tsx
Labels: ✨ feat

#181 feat : 리딩 디테일 페이지 북마크 생성, 삭제에 optimistic update 적용
  src/api/hooks/useBookmarks.ts
  src/components/reading/ReadingScriptItem.tsx
  src/hooks/useHandleBookmark.ts
Labels: 🌝 fe

#182 refactor : 리스닝 페이지 북마크 메모를 하나로 합치고 현재 자막으로 윈도우가 스크롤 되던 문제 해결
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/components/listening/BookmarkMemoItem.tsx
  src/components/listening/BookmarkMemoPanel.tsx
  src/components/listening/scriptPlayer/BlockView.tsx
  src/components/listening/scriptPlayer/LineView.tsx
  src/components/listening/scriptPlayer/TextDisplay.tsx
  src/components/listening/scriptPlayer/index.tsx
  src/components/reading/ReadingScriptItem.tsx
  src/hooks/useHandleBookmark.ts
  src/types/ContentDetail.ts
Labels: 🌝 fe, ✨ feat, 🐞 fix, ⚒️ refactor

#183 feat : optimistic update수정.onMutate, onError, onSettled 속성으로 구현
  src/api/hooks/useBookmarks.ts
Labels: 🌝 fe, ✨ feat
