Repository Kernel360/F2-BIENGUAL-FE, pull requests merged in 2024-11, with the labels that each got.

#187 [feat] isScrapped에 맞춰 스크랩 로직 수정, 스크랩 버튼에도 로그인 모달 추가, 리딩 preview에도 scrap버튼 만듦
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/app/(default)/learn/listening/page.tsx
  src/app/(default)/learn/reading/page.tsx
  src/app/(default)/scrapbook/layout.tsx
  src/app/(default)/search/page.tsx
  src/components/HomePageClient.tsx
  src/components/ItemComponent.tsx
  src/components/PreviewScrapButton.tsx
  src/components/common/Modal.tsx
  src/components/items/ListItem.tsx
  src/hooks/useHandleScrap.ts
  src/providers/QueryClientProvider.tsx
  src/types/Preview.ts
Labels: 🌝 fe, ✨ feat

#188 feat : 개발한 react-player-plugin-prompter 오픈소스 라이브러리를 import 해서 사용하도록 변경
  package-lock.json
  package.json
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/components/listening/SubtitleOption.tsx
  src/components/listening/scriptPlayer/BlockView.tsx
  src/components/listening/scriptPlayer/Button.tsx
  src/components/listening/scriptPlayer/LineView.tsx
  src/components/listening/scriptPlayer/TextDisplay.tsx
  src/components/listening/scriptPlayer/index.tsx
  src/types/Scripts.ts
Labels: 🌝 fe, ✨ feat, ⚒️ refactor

#190 feat : 여러 경로에서 스크랩 기능의 낙관적 업데이트 및 페이지네이션 캐시 관리 개선
  src/api/hooks/usePreview.ts
  src/app/(default)/learn/listening/page.tsx
  src/app/(default)/learn/reading/page.tsx
  src/components/HomePageClient.tsx
  src/components/PreviewScrapButton.tsx
  src/components/common/ContentTypeFilter.tsx
  src/hooks/useHandleScrap.ts
  src/hooks/useScrapToggle.ts
Labels: 🌝 fe, ✨ feat, 🐞 fix, ⚒️ refactor

#196 [feat] 변경된 데이터 구조에 맞춰 bookmark훅에 대한optimistic update로직을 수정
  src/api/hooks/useBookmarks.ts
  src/components/reading/ReadingScriptItem.tsx
  src/hooks/useHandleBookmark.ts
Labels: 🌝 fe, ✨ feat

#197 feat : 유저 미션 상태 확인 및 완료 요청 api 훅 생성
  src/api/hooks/useMission.ts
  src/api/hooks/useScrap.ts
  src/api/queries/missionQueries.ts
  src/api/queries/scrapQueries.ts
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/app/(default)/learn/reading/detail/[id]/page.tsx
  src/types/ContentDetail.ts
  src/types/Mission.ts
  src/types/Scrap.ts
Labels: 🌝 fe, ✨ feat, ⚒️ refactor

#201 feat : 하루 중 첫 콘텐츠 90%이상 학습, 북마크 생성인 경우 미션 완료 요청 보내기
  src/api/hooks/useMission.ts
  src/api/queries/missionQueries.ts
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/app/(default)/learn/reading/detail/[id]/page.tsx
  src/components/common/ScrollProgressBar.tsx
  src/components/listening/BookmarkMemoPanel.tsx
  src/components/listening/VideoPlayer.tsx
  src/components/reading/MissionScrollProgressbar.tsx
  src/components/reading/ReadingScriptItem.tsx
  src/hooks/useScrollProgress.ts
Labels: 🌝 fe, ✨ feat

#202 [feat] 대시보드 히스토리 달력 컴포넌트 UI 구현, 학습트래커 일일미션상태api연결
  .eslintrc.json
  package-lock.json
  package.json
  src/app/(default)/dashboard/page.tsx
  src/components/common/CustomShadcnCalendar.tsx
  src/components/common/DashboardCalendar.tsx
  src/components/layout/ContentWrapper.tsx
  src/components/layout/Header.tsx
  src/components/layout/SideArea.tsx
  src/components/layout/side/LearningTracker.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/lib/formatDate.ts
Labels: 🌝 fe, ✨ feat, 🌈design

#207 feat : 카테고리 api 연결
  src/api/hooks/useCategories.ts
  src/api/queries/fetchAllCategories.ts
  src/api/queries/userQueries.ts
  src/app/(default)/mypage/profile/page.tsx
  src/app/(fullscreen)/layout.tsx
  src/app/(fullscreen)/login/add/page.tsx
  src/components/ui/accordion.tsx
  src/components/ui/button.tsx
  src/types/Category.ts
  src/types/User.ts
Labels: 🌝 fe, ✨ feat

#206 fix : 북마크 생성 요청이 성공 하고 나서 미션 업데이터 요청 보내도록 수정
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/app/(default)/learn/listening/page.tsx
  src/app/(default)/learn/reading/detail/[id]/page.tsx
  src/app/(default)/learn/reading/page.tsx
  src/app/(default)/search/page.tsx
  src/components/ItemComponent.tsx
  src/components/PreviewScrapButton.tsx
  src/components/listening/BookmarkMemoPanel.tsx
  src/components/reading/ReadingScriptItem.tsx
  src/hooks/useHandleBookmark.ts
  src/hooks/useScrapToggle.ts
Labels: 🌝 fe, 🐞 fix

#209 design : login/add페이지 ui develop
  src/app/(fullscreen)/login/add/page.tsx
Labels: 🌝 fe, 🌈design

#212 feat : mock 데이터로 대시 보드 페이지 차트 UI 구현
  package-lock.json
  package.json
  src/app/(default)/dashboard/page.tsx
  src/components/ui/card.tsx
  src/components/ui/chart.tsx
Labels: 🌝 fe, ✨ feat

#214 211 feat create category filter component
  src/app/(default)/learn/listening/page.tsx
  src/app/(default)/learn/reading/page.tsx
  src/components/common/ContentTypeFilter.tsx
Labels: 🌝 fe, ✨ feat, 🌈design

#216 feat : 정렬 버튼 추가
  package-lock.json
  package.json
  src/components/common/ContentTypeFilter.tsx
  src/components/ui/select.tsx
Labels: 🌝 fe, ✨ feat, 💄 style

#218 design : 다른사람이 저장한 문장 캐러셀 컴포넌트 ui구현
  src/components/HomePageClient.tsx
  src/components/SentenceComponent.tsx
Labels: 🌈design

#224 feat: 최근 콘텐츠 포인트 차감 안내 커버와 모달 구현
  src/app/(default)/learn/listening/page.tsx
  src/app/(default)/learn/reading/page.tsx
  src/components/HomePageClient.tsx
  src/components/ItemComponent.tsx
  src/components/ItemComponentCard.tsx
  src/components/ItemComponentList.tsx
  src/components/common/PointCover.tsx
  src/components/items/ContentCard.tsx
  src/components/items/ListItem.tsx
  src/components/layout/side/LearningTracker.tsx
  src/types/Preview.ts
Labels: 🌝 fe, ✨ feat

#225 feat : 최근 학습 콘텐츠 목록 페이지 구현
  package-lock.json
  src/api/hooks/useDashboard.ts
  src/api/queries/dashboardQueries.ts
  src/app/(default)/dashboard/learning/recent/page.tsx
  src/app/(default)/dashboard/page.tsx
  src/components/items/ContentCard.tsx
  src/types/Dashboard.ts
Labels: 🌝 fe, ✨ feat

#227 feat : 반응형 ui 적용 중
  package-lock.json
  package.json
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/components/layout/MobileNav.tsx
  src/components/layout/SideArea.tsx
  src/components/layout/side/LearningTracker.tsx
  src/components/layout/side/MobileLearningTracker.tsx
  src/components/listening/BookmarkMemoPanel.tsx
  src/components/listening/SubtitleOption.tsx
  src/components/listening/VideoPlayer.tsx
  src/components/ui/tooltip.tsx
Labels: 🌝 fe, ✨ feat, 🌈design

#229 refactor : API 요청 함수를 apiClient로 리팩터링 및 학습 미션 중복 업데이트 방지
  src/api/hooks/useCategories.ts
  src/api/queries/bookmarkQueries.ts
  src/api/queries/categoryQueries.ts
  src/api/queries/contentsQueries.ts
  src/api/queries/dashboardQueries.ts
  src/api/queries/fetchAllCategories.ts
  src/api/queries/learningProgressQueries.ts
  src/api/queries/missionQueries.ts
  src/api/queries/quizQueries.ts
  src/api/queries/scrapQueries.ts
  src/api/queries/searchQuries.ts
  src/api/queries/userQueries.ts
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/app/(default)/mypage/profile/page.tsx
  src/components/reading/MissionScrollProgressbar.tsx
  src/lib/apiClient.ts
Labels: 🌝 fe, ✨ feat, ⚒️ refactor, 🖊️rename

#232 feat : Carousel 컴포넌트가 부모 요소의 너비에 따라 반응형으로 조절되도록 수정
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/components/HomePageClient.tsx
  src/components/SentenceComponent.tsx
  src/components/common/Carousel.tsx
  src/components/layout/ContentWrapper.tsx
  src/components/quiz/QuizCarousel.tsx
Labels: 🌝 fe, ✨ feat, 🐞 fix

#231 design : 포인트 페이지 월별 데이터 불러오는 화면으로 UI수정
  src/app/(default)/point/page.tsx
Labels: 🌈design

#238 feat : 리스닝디테일, 리딩디테일에 메타데이터 설정
  src/app/(default)/learn/listening/detail/ListeningDetail.tsx
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/app/(default)/learn/reading/detail/ReadingDetail.tsx
  src/app/(default)/learn/reading/detail/[id]/page.tsx
Labels: ✨ feat

#237 feat : 변경된 퀴즈 데이터 구조에 맞게 컴포넌트 수정
  src/api/hooks/useQuiz.ts
  src/api/queries/quizQueries.ts
  src/app/(default)/learn/listening/detail/ListeningDetailClient.tsx
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/app/(default)/learn/reading/detail/ReadingDetailClient.tsx
  src/app/(default)/learn/reading/detail/[id]/page.tsx
  src/components/quiz/BlankQuiz.tsx
  src/components/quiz/GeneralQuiz.tsx
  src/components/quiz/OrderQuiz.tsx
  src/components/quiz/Quiz.tsx
  src/components/quiz/QuizCarousel.tsx
  src/types/Quiz.ts
Labels: 🌝 fe, ✨ feat

#244 [design] duration api연결 , 컨텐츠타입 뱃지 만듦
  src/app/(default)/dashboard/learning/recent/page.tsx
  src/app/(default)/scrapbook/content/page.tsx
  src/app/(default)/search/page.tsx
  src/components/ItemComponentCard.tsx
  src/components/ItemComponentList.tsx
  src/types/Dashboard.ts
  src/types/Preview.ts
  src/types/Scrap.ts
Labels: 🌈design

#245 [feat] 디테일페이지,카테고리필터 PrefetchQuery로 SSR적용
  src/app/(default)/learn/layout.tsx
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/app/(default)/learn/listening/page.tsx
  src/app/(default)/learn/reading/detail/[id]/page.tsx
  src/app/(default)/learn/reading/page.tsx
  src/components/common/ContentTypeFilter.tsx
  src/components/listening/VideoPlayer.tsx
Labels: ✨ feat, ⚒️ refactor

#246 feat : 틀린 문제 다시 푸는 기능 구현
  package-lock.json
  package.json
  src/api/queries/quizQueries.ts
  src/app/(default)/learn/listening/detail/ListeningDetailClient.tsx
  src/app/(default)/learn/reading/detail/ReadingDetailClient.tsx
  src/components/quiz/GeneralQuiz.tsx
  src/components/quiz/OrderQuiz.tsx
  src/components/quiz/Quiz.tsx
  src/components/quiz/QuizCarousel.tsx
  src/stores/quizStore.ts
Labels: 🌝 fe, ✨ feat

#248 [fix] 페이지네이션도 url state 유지되도록 설정
  src/app/(default)/learn/listening/page.tsx
  src/app/(default)/learn/reading/page.tsx
  src/components/common/ContentTypeFilter.tsx
  src/hooks/useSetSearchParams.ts
Labels: 🐞 fix, ⚒️ refactor

#255 feat : 현재 월의 학습한 콘텐츠 카테고리 비율을 파이 차트로 보여줌
  src/api/hooks/useDashboard.ts
  src/api/queries/dashboardQueries.ts
  src/app/(default)/dashboard/page.tsx
  src/lib/formatDate.ts
  src/lib/processCategoryData.ts
  src/types/Dashboard.ts
Labels: 🌝 fe, ✨ feat

#256 [feat] 학습트래커, 대시보드 달력에 미션히스토리api연결
  src/api/hooks/useDashboard.ts
  src/api/hooks/useMission.ts
  src/api/queries/contentsQueries.ts
  src/api/queries/dashboardQueries.ts
  src/api/queries/missionQueries.ts
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/app/(default)/learn/reading/detail/[id]/page.tsx
  src/components/common/DashboardCalendar.tsx
  src/components/layout/side/LearningTracker.tsx
  src/components/layout/side/MobileLearningTracker.tsx
  src/types/Dashboard.ts
  src/types/Mission.ts
Labels: ✨ feat, 🐞 fix

#260 [fix] missionHistory의 DB기록 날짜와 선택한날짜가 다른데에서 오는 날짜 오류 정정
  src/app/(default)/dashboard/learning/recent/page.tsx
  src/app/(default)/dashboard/page.tsx
  src/app/(default)/point/page.tsx
  src/app/(default)/scrapbook/content/page.tsx
  src/app/(default)/search/page.tsx
  src/components/ItemComponentCard.tsx
  src/components/common/ContentPreview.tsx
  src/components/common/DashboardCalendar.tsx
  src/components/common/MemoItem.tsx
  src/components/layout/side/LearningTracker.tsx
  src/components/layout/side/MobileLearningTracker.tsx
  src/components/listening/BookmarkMemoItem.tsx
  src/components/listening/BookmarkMemoPanel.tsx
  src/components/listening/ControlBar.tsx
  src/lib/convertTime.ts
  src/lib/formDateToMonthDay.ts
  src/lib/formatDate.ts
  src/lib/formatTime.ts
  src/lib/formatViewCount.ts
  src/lib/shuffleArray.ts
  src/lib/utils.ts
Labels: 🐞 fix

#262 feat : 퀴즈 정답율 api 연결 및 대시보드 바 차트 구현
  src/api/hooks/useDashboard.ts
  src/api/queries/dashboardQueries.ts
  src/app/(default)/dashboard/page.tsx
  src/lib/formatDate.ts
  src/lib/processChartData.ts
  src/types/Dashboard.ts
Labels: 🌝 fe, ✨ feat

#264 feat : 대시보드 포인트 api 연결
  src/api/hooks/useDashboard.ts
  src/api/queries/dashboardQueries.ts
  src/app/(default)/dashboard/page.tsx
  src/app/(default)/point/page.tsx
  src/lib/constants/point.ts
  src/types/Dashboard.ts
Labels: 🌝 fe, ✨ feat

#267 243 feat add completelearningrate to when we use progressbar
  src/app/(default)/learn/listening/detail/ListeningDetailClient.tsx
  src/app/(default)/learn/reading/detail/ReadingDetailClient.tsx
  src/components/layout/side/LearningTracker.tsx
  src/types/ContentDetail.ts
Labels: ✨ feat, ⚙️ chore

#270 [design] 모바일 반응형
  src/app/(default)/dashboard/learning/recent/page.tsx
  src/app/(default)/learn/listening/detail/ListeningDetailClient.tsx
  src/app/(default)/learn/listening/page.tsx
  src/app/(default)/learn/reading/detail/ReadingDetailClient.tsx
  src/app/(default)/scrapbook/content/page.tsx
  src/app/(default)/scrapbook/highlight/page.tsx
  src/app/(default)/scrapbook/layout.tsx
  src/app/(default)/search/page.tsx
  src/components/ItemComponentCard.tsx
  src/components/items/ContentCard.tsx
  src/components/listening/BookmarkMemoPanel.tsx
  src/lib/formatViewCount.ts
  src/types/Scrap.ts
Labels: 🌈design

#271 refactor : 대시보드를 패널 컴포넌트 분리 및 날짜 함수 리팩토링
  src/app/(default)/dashboard/page.tsx
  src/app/(default)/point/page.tsx
  src/app/(default)/scrapbook/content/page.tsx
  src/components/common/ContentPreview.tsx
  src/components/common/DashboardCalendar.tsx
  src/components/common/MemoItem.tsx
  src/components/common/Panels.tsx
  src/components/dashboard/CategoryDistributionPanel.tsx
  src/components/dashboard/CurrentPointsPanel.tsx
  src/components/dashboard/MissionCalendar.tsx
  src/components/dashboard/QuizAccuracyPanel.tsx
  src/components/dashboard/RecentLearningPanel.tsx
  src/components/layout/side/LearningTracker.tsx
  src/components/layout/side/MobileLearningTracker.tsx
  src/lib/formatDate.ts
Labels: 🌝 fe, ✨ feat, ⚒️ refactor

#276 feat : 관심사 기반 추천 콘텐츠 랭킹 컴포넌트 구현
  README.md
  src/api/hooks/useRecommend.ts
  src/api/queries/recommendQueries.ts
  src/app/(default)/learn/listening/page.tsx
  src/app/(default)/learn/reading/page.tsx
  src/app/(fullscreen)/admin/create/listening/page.tsx
  src/app/(fullscreen)/admin/layout.tsx
  src/app/(fullscreen)/login/add/page.tsx
  src/components/HomePageClient.tsx
  src/components/RecommendedList.tsx
  src/components/common/Carousel.tsx
  src/components/common/DisabledModal.tsx
  src/components/common/LogInOutButton.tsx
  src/components/common/Modal.tsx
  src/lib/constants/point.ts
  src/types/Preview.ts
Labels: 🌝 fe, ✨ feat

#282 fix : 쿠키 다시 박아넣어서 로그인 상태 유지하기
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/app/(default)/learn/reading/detail/[id]/page.tsx
  src/app/(default)/page.tsx
Labels: 🐞 fix

#284 refactor : 퀴즈 로직을 기존의 상태 기반에서 이벤트 기반으로 useReducer 사용해서 리팩토링
  src/api/hooks/useQuiz.ts
  src/app/(default)/learn/listening/detail/ListeningDetailClient.tsx
  src/app/(default)/learn/listening/detail/[id]/page.tsx
  src/app/(default)/learn/reading/detail/ReadingDetailClient.tsx
  src/app/(default)/learn/reading/detail/[id]/page.tsx
  src/components/common/PointCover.tsx
  src/components/layout/side/LearningTracker.tsx
  src/components/quiz/GeneralQuiz.tsx
  src/components/quiz/OrderQuiz.tsx
  src/components/quiz/Quiz.tsx
  src/components/quiz/QuizCarousel.tsx
  src/components/quiz/QuizWrapper.tsx
  src/lib/quizReducer.ts
  src/types/Quiz.ts
Labels: 🌝 fe, ✨ feat, ⚒️ refactor

#286 feat: carousel 갭 추가
  src/components/HomePageClient.tsx
  src/components/common/PointCover.tsx
  src/components/items/ContentCard.tsx
Labels: 🌝 fe, ✨ feat

#290 fix : 카테고리 prefetch로직 삭제
  src/app/(default)/learn/layout.tsx
Labels: 🌝 fe, 🐞 fix

#294 [fix] 포인트 페이지 에러 수정, 로고 추가 등 자잘한 에러 수정
  src/app/(default)/mypage/profile/page.tsx
  src/app/(default)/point/page.tsx
  src/app/favicon.ico
  src/app/icon.png
  src/components/layout/Header.tsx
Labels: 🐞 fix

#293 fix : 대시보드 차트 빈 데이터 처리 및 404 페이지 구현
  src/app/(default)/dashboard/page.tsx
  src/app/(default)/layout.tsx
  src/app/(fullscreen)/layout.tsx
  src/app/(fullscreen)/login/add/page.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/components/RecommendedList.tsx
  src/components/SentenceComponent.tsx
  src/components/common/Panels.tsx
  src/components/dashboard/CategoryDistributionPanel.tsx
  src/components/dashboard/QuizAccuracyPanel.tsx
  src/components/dashboard/RecentLearningPanel.tsx
Labels: 🌝 fe, ✨ feat, 🐞 fix

#296 fix : pagination problem and add bug form
  src/app/(default)/learn/reading/page.tsx
  src/components/HomePageClient.tsx
Labels: 🌝 fe, ✨ feat, 🐞 fix

#299 feat: 카테고리 컨텐츠타입별로 불러오도록 수정
  src/api/hooks/useCategories.ts
  src/api/queries/categoryQueries.ts
  src/components/common/ContentTypeFilter.tsx
Labels: ✨ feat

#301 fix: 스크랩, 대시보드 페이지 로그인 모달 x 버튼 클릭시 홈으로 리다이렉트
  src/app/(default)/dashboard/page.tsx
  src/app/(default)/scrapbook/layout.tsx
  src/components/HomePageClient.tsx
  src/components/layout/side/LearningTracker.tsx
Labels: 🌝 fe, 🐞 fix

#304 feat : 에러 로그 찍는 sentry 설치
  .gitignore
  next.config.mjs
  package-lock.json
  package.json
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/api/sentry-example-api/route.ts
  src/app/global-error.tsx
  src/app/sentry-example-page/page.tsx
  src/instrumentation.ts
Labels: 🌝 fe, ✨ feat

#309 fix : useScrapToggle에 낙관적 업데이트를 위해 queryKey를 넘기는 방식으로 수정
  src/api/hooks/usePreview.ts
  src/app/(default)/learn/listening/detail/ListeningDetailClient.tsx
  src/app/(default)/learn/listening/page.tsx
  src/app/(default)/learn/reading/detail/ReadingDetailClient.tsx
  src/app/(default)/learn/reading/page.tsx
  src/components/ItemComponentCard.tsx
  src/components/ItemComponentList.tsx
  src/components/PreviewScrapButton.tsx
  src/components/common/PointCover.tsx
  src/components/items/ContentCard.tsx
  src/hooks/useScrapToggle.ts
Labels: 🌝 fe, 🐞 fix, ⚒️ refactor

#310 [fix] 리딩 리스닝 전환될 때 없는 카테고리는 빈 화면 보여주는 문제 해결
  src/components/common/ContentTypeFilter.tsx
  src/components/common/MemoItem.tsx
Labels: 🌝 fe, 🐞 fix

#312 [fix] 나중에 고를래요 누르면 빈 배열 보내게 만들기
  src/app/(fullscreen)/login/add/page.tsx
Labels: 🐞 fix

#319 fix : 달 이동해도 자꾸 11월만 보여주는 문제 해결
  src/components/dashboard/MissionCalendar.tsx
Labels: 🌝 fe, 🐞 fix

#324 [design] 캘린더 디자인 변경
  src/components/StatusBox.tsx
  src/components/common/CustomShadcnCalendar.tsx
  src/components/dashboard/MissionCalendar.tsx
Labels: 🌈design

#322 fix : 스크랩 페이지 형광펜 수정시 롤백이 안되던 버그 수정
  src/app/(default)/scrapbook/layout.tsx
  src/components/common/MemoItem.tsx
Labels: 🌝 fe, 🐞 fix

#329 chore: pwa를 위한 manifest 파일 작성
  public/icon-192x192.png
  public/icon-512x512.png
  src/app/manifest.ts
Labels: 🌝 fe, ⚙️ chore

#330 [fix] 디테일페이지 동적라우팅 [id]에 이상한 url입력하면 뜨는 status404 뜨면서 화면 뻗는 문제 해결
  src/app/(default)/learn/listening/detail/[id]/error.tsx
  src/app/(default)/learn/reading/detail/[id]/error.tsx
Labels: 🐞 fix

#332 design : 난이도 컴포넌트 하트 아이콘로 변경
  src/components/DifficultyDisplay.tsx
Labels: 🌝 fe, 🌈design

#335 334 chore modify apiclient with customerror and make errortsx for detail page
  src/api/customError.ts
  src/api/customErrorClass.ts
  src/app/(default)/learn/listening/detail/[id]/error.tsx
  src/app/(default)/learn/reading/detail/[id]/error.tsx
  src/app/global-error.tsx
  src/app/not-found.tsx
  src/lib/apiClient.ts
Labels: 🌝 fe, ⚙️ chore

#342 feat : 컨트롤바 반응형 디자인 맞춤, 음소거 버튼 구현, 선택한 속도 옆에 보여줌
  src/components/listening/ControlBar.tsx
  src/components/listening/VideoPlayer.tsx
Labels: 🌝 fe, ✨ feat, 🌈design

#340 refactor : 포인트 차감 과정을 사용자가 알 수 있도록 수정, 캐러셀 포인트 커버 넓이 안 맞던 것 수정
  src/api/hooks/usePoint.ts
  src/api/queries/pointQueries.ts
  src/app/(default)/learn/listening/detail/[id]/error.tsx
  src/app/(default)/learn/reading/detail/[id]/error.tsx
  src/components/HomePageClient.tsx
  src/components/SentenceComponent.tsx
  src/components/common/Carousel.tsx
  src/components/common/DisabledModal.tsx
  src/components/common/Modal.tsx
  src/components/common/PointCover.tsx
  src/components/items/ContentCard.tsx
  src/types/Point.ts
Labels: 🌝 fe, ✨ feat, 🐞 fix, ⚒️ refactor

#343 feat : 퀴즈 힌트 보기 기능 추가
  src/api/hooks/useQuiz.ts
  src/api/queries/quizQueries.ts
  src/components/quiz/GeneralQuiz.tsx
  src/components/quiz/OrderQuiz.tsx
  src/types/Quiz.ts
Labels: 🌝 fe, ✨ feat

#345 [feat] 캐러셀 자동으로 옆으로 움직이도록 만듦
  src/components/HomePageClient.tsx
  src/components/common/Carousel.tsx
Labels: 🌝 fe, ✨ feat, 🌈design

#346 feat : 닉네임 유효성 검사
  src/app/(default)/mypage/profile/page.tsx
Labels: 🌝 fe, ✨ feat
