Repository Kernel360/F2-BIENGUAL-FE, pull requests merged in 2024-09, with the labels that each got.

#6 feat: 공통 레이아웃(Header, Mobile Nav) 구현 및 shadcn 컴포넌트 적용
  .eslintrc.json
  package-lock.json
  package.json
  src/app/layout.tsx
  src/components/Header.tsx
  src/components/MobileNav.tsx
  src/components/ui/button.tsx
Labels: ✨ feat, ⚙️ chore

#8 feat: /mypage 경로에 공통 레이아웃 적용
  src/app/mypage/challenges/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/learn/page.tsx
  src/app/mypage/page.tsx
  src/components/Header.tsx
Labels: ✨ feat, 🌈design

#10 feat : 컨텐츠 담는 Card 컴포넌트 구현
  package-lock.json
  package.json
  src/app/learn/page.tsx
  src/components/Cards.tsx
  src/components/ui/aspect-ratio.tsx
  src/components/ui/badge.tsx
  src/components/ui/card.tsx
  src/lib/utils.ts
  src/mock/cardData.json
Labels: 🌝 FE, ✨ feat, 🌈design

#16 feat : 리스닝 미리 보기 컴포넌트 수정
  src/app/globals.css
  src/app/learn/listening/page.tsx
  src/app/learn/page.tsx
  src/components/Cards.tsx
  src/components/ContentsCard.tsx
  src/components/Header.tsx
  src/components/ui/card.tsx
  src/mock/cardData.json
Labels: 🌈design

#15 feat : 리딩 컨텐츠 미리보기 컴포넌트 구현
  .github/PULL_REQUEST_TEMPLATE.md
  next.config.mjs
  src/app/learn/reading/page.tsx
  src/components/ReadingPreview.tsx
  src/mock/readingContentData.json
  tsconfig.json
Labels: ✨ feat

#19 feat: Storybook에 Input 컴포넌트 스토리 작성
  .storybook/preview.ts
  src/components/Input/Input.stories.tsx
  src/components/Input/Input.tsx
  src/components/ui/input.tsx
Labels: ✨ feat, 🌈design
