Repository Kernel360/F2-BIENGUAL-FE, pull requests merged in 2024-12, with the labels that each got.

#349 [feat] 캐러셀에 loop기능 넣어서 마지막인덱스랑 첫 인덱스랑 이어진 것처럼 만들기
  src/components/common/Carousel.tsx
Labels: 🌝 fe, ✨ feat

#348 test : 테스트를 위한 jest 설치, 세팅, 404페이지 간단한 테스트 코드 작성
  __tests__/pages/404.test.tsx
  jest.config.ts
  jest.setup.ts
  package-lock.json
  package.json
  src/app/not-found.tsx
Labels: 🌝 fe, ✅ test, ⚙️ chore

#351 feat: sentences banner에 api 연결 , loop 기능 반영된 extended 캐러셀에 initialData 적용하여 미리 불러오기
  src/api/hooks/useRecommend.ts
  src/api/queries/recommendQueries.ts
  src/app/(default)/page.tsx
  src/components/HomePageClient.tsx
  src/components/SentenceComponent.tsx
  src/components/common/Carousel.tsx
  src/types/Preview.ts
Labels: 🌝 fe, ✨ feat, ⚒️ refactor, ⚙️ chore

#350 feat : 로그아웃 상태일 때 학습 트래커 블러 처리
  src/components/layout/side/LearningTracker.tsx
  src/components/layout/side/MobileLearningTracker.tsx
Labels: 🌝 fe, ✨ feat

#354 feat : react player plugin prompter 버전 업에 따른 코드 수정
  package-lock.json
  package.json
  src/app/(default)/learn/listening/detail/ListeningDetailClient.tsx
  src/components/listening/VideoPlayer.tsx
Labels: 🌝 fe, ✨ feat, ⚙️ chore

#356 chore : main페이지 sentene데이터에도 initialData적용, design : 러닝트래커 수정
  src/app/(default)/page.tsx
  src/components/HomePageClient.tsx
  src/components/SentenceComponent.tsx
  src/components/common/Carousel.tsx
  src/components/common/LogInOutButton.tsx
  src/components/dashboard/MissionCalendar.tsx
  src/components/layout/MobileNav.tsx
  src/components/layout/side/LearningTracker.tsx
  src/components/layout/side/MobileLearningTracker.tsx
Labels: 🌝 fe, 🌈design, ⚙️ chore

#361 [fix] reset to previous global-error
  src/app/global-error.tsx
Labels: 🌝 fe, 🐞 fix

#363 test : playwright 회원가입 플로우 테스트, jest 퀴즈 상태 관리 리듀서 테스트 작성
  .gitignore
  e2e/demo-todo-app.spec.ts
  e2e/example.spec.ts
  e2e/signup-without-category.spec.ts
  e2e/signup.spec.ts
  package-lock.json
  package.json
  playwright.config.ts
  src/api/queries/searchQuries.ts
  src/components/quiz/GeneralQuiz.tsx
  src/components/quiz/OrderQuiz.tsx
  src/stores/quizStore.ts
  tests/pages/404.test.tsx
  tests/utils/quizReducer.test.ts
Labels: 🌝 fe, ✅ test

#369 [refactor] learn/reading, learn/listening 페이지에 prefetchQuery구문 도입하여 LCP지연로딩 문제 개선
  src/app/(default)/learn/layout.tsx
  src/app/(default)/learn/listening/LearnListeningClient.tsx
  src/app/(default)/learn/listening/page.tsx
  src/app/(default)/learn/reading/LearnReadingClient.tsx
  src/app/(default)/learn/reading/page.tsx
  src/components/common/CustomShadcnCalendar.tsx
  src/components/ui/avatar.tsx
  src/components/ui/card.tsx
  src/components/ui/chart.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/tooltip.tsx
Labels: 🌝 fe, ⚒️ refactor

#370 fix : 모바일에서 차트 깨지던 현상 해결, ios 기기일 때 모바일 하단 넷바에 padding bottom 줌
  src/app/(default)/dashboard/page.tsx
  src/components/dashboard/CategoryDistributionPanel.tsx
  src/components/dashboard/QuizAccuracyPanel.tsx
  src/components/layout/MobileNav.tsx
  src/lib/processChartData.ts
Labels: 🌝 fe, ✨ feat, 🐞 fix, 🌈design

#373 fix : contentType에서 url이동하기 전에 카테고리 색깔 변경되는 문제 해결
  src/components/common/ContentTypeFilter.tsx
Labels: 🌝 fe, 🐞 fix

#374 feat : 오프라인에서 캐시를 사용할 수 있도록 서비스 워커 파일 추가
  public/offline.html
  public/sw.js
  src/components/HomePageClient.tsx
  src/components/layout/MobileNav.tsx
  tsconfig.json
Labels: 🌝 fe, ✨ feat

#377 fix : 리딩 북마크 메모 아이템, 아이콘 위치 수정
  src/app/(default)/dashboard/learning/recent/page.tsx
  src/app/(default)/layout.tsx
  src/components/HomePageClient.tsx
  src/components/common/LoadingSpinner.tsx
  src/components/common/MemoInput.tsx
  src/components/common/Tooltip.tsx
  src/components/reading/ReadingScriptItem.tsx
Labels: 🌝 fe, 🐞 fix

#381 refactor : 번들 사이즈 줄이고 lighthouse 성능 지표, LCP 개선
  next.config.mjs
  package-lock.json
  package.json
  public/sw.js
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/api/hooks/useRecommend.ts
  src/app/(default)/layout.tsx
  src/app/(default)/page.tsx
  src/app/api/sentry-example-api/route.ts
  src/app/sentry-example-page/page.tsx
  src/components/HomePageClient.tsx
  src/components/RecommendedList.tsx
  src/components/ui/carousel.tsx
  src/instrumentation.ts
  src/lib/constants/mockRecommendedData.ts
Labels: 🌝 fe, ⚒️ refactor, ⚙️ chore

#389 fix: 추천 콘텐츠 모달 위치 수정
  src/components/RecommendedList.tsx
Labels: 🌝 fe, 🐞 fix

#390 fix : 캐러셀 이동 버튼 마구 누르면 애니메이션 동작 꼬이는 문제 해결, 캐러셀 이동 버튼 직접누르면 autoPlay가 …
  src/components/common/Carousel.tsx
Labels: 🌝 fe, 🐞 fix

#394 fix : 포인트 필요한 콘텐츠 열람 후 포인트 커버 사라지지 않던 문제 해결
  src/api/hooks/usePoint.ts
  src/api/queries/contentsQueries.ts
  src/app/(default)/learn/listening/page.tsx
  src/app/(default)/learn/reading/page.tsx
  src/components/layout/MobileSearch.tsx
Labels: 🌝 fe, 🐞 fix

#397 fix : nextjs 기본 fetch 설정은 cache-force에서 no-store로 변경함으로써 카테고리 최신 업데이트…
  src/lib/apiClient.ts
Labels: 🌝 fe, 🐞 fix

#401 fix : 리딩디테일에서 난이도 제출해도 안 받아왔던 문제 해결
  src/app/(default)/learn/reading/detail/ReadingDetailClient.tsx
Labels: 🌝 fe, 🐞 fix

#399 design : 리스닝, 리딩 디테일 페이지 UI 통일, 헤더 유저 드롭다운 스타일 수정
  src/app/(default)/learn/layout.tsx
  src/app/(default)/learn/listening/detail/ListeningDetailClient.tsx
  src/app/(default)/learn/reading/detail/ReadingDetailClient.tsx
  src/app/(default)/search/page.tsx
  src/components/DifficultyDisplay.tsx
  src/components/layout/Header.tsx
  src/components/layout/MobileNav.tsx
  src/components/layout/MobileSearch.tsx
  src/components/reading/ReadingScriptItem.tsx
Labels: 🌝 fe, 🌈design

#403 feat: 검색어 20자 길이 제한
  src/components/common/SearchComponent.tsx
  src/components/layout/MobileSearch.tsx
Labels: 🌝 fe, ✨ feat

#405 refactor : flag로 분기하고, sideArea코드는 독립적으로 반응형으로 보이도록 리팩토링
  src/components/layout/ContentWrapper.tsx
Labels: 🌝 fe, ⚒️ refactor

#408 392 fix design errors
  src/app/(default)/learn/listening/detail/ListeningDetailClient.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/common/FloatingButtons.tsx
  src/components/layout/ContentWrapper.tsx
  src/components/layout/Header.tsx
  src/components/layout/side/LearningTracker.tsx
Labels: 🌝 fe, 🐞 fix, 🌈design

#410 fix : 캐러셀 컴포넌트 보여줘야하는 개수를 받도록 수정, 폴백 폰트 설정, 추천 콘텐츠 디자인 수정
  src/app/(default)/layout.tsx
  src/app/(default)/learn/listening/detail/ListeningDetailClient.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/HomePageClient.tsx
  src/components/RecommendedList.tsx
  src/components/common/Carousel.tsx
  src/components/common/PointCover.tsx
  src/components/quiz/QuizWrapper.tsx
  tailwind.config.ts
Labels: 🌝 fe, 🐞 fix, ⚒️ refactor, 🌈design

#411 [refactor] prefetchQuery 나머지 페이지에 적용
  src/api/queries/bookmarkQueries.ts
  src/api/queries/dashboardQueries.ts
  src/api/queries/missionQueries.ts
  src/api/queries/scrapQueries.ts
  src/api/queries/userQueries.ts
  src/app/(default)/dashboard/learning/recent/DashboardRecentLearningClient.tsx
  src/app/(default)/dashboard/learning/recent/page.tsx
  src/app/(default)/layout.tsx
  src/app/(default)/scrapbook/SideNav.tsx
  src/app/(default)/scrapbook/content/ContentClient.tsx
  src/app/(default)/scrapbook/content/page.tsx
  src/app/(default)/scrapbook/highlight/HighlightClient.tsx
  src/app/(default)/scrapbook/highlight/page.tsx
  src/app/(default)/scrapbook/layout.tsx
  src/components/dashboard/CategoryDistributionPanel.tsx
  src/components/dashboard/QuizAccuracyPanel.tsx
  src/providers/QueryClientProvider.tsx
Labels: 🌝 fe, ⚒️ refactor

#413 design: 자막 넘기기 버튼 스타일 수정
  src/app/(default)/learn/listening/detail/ListeningDetailClient.tsx
Labels: 🌝 fe, 🌈design

#417 design : 추천콘텐츠에서 로그인하라는 모달 뜰때 보이는 mockdata 배경에 흰색 더 짙게 넣기
  src/components/RecommendedList.tsx
Labels: 🌝 fe, 🌈design

#415 refactor: mypage에도 prefetchQuery적용, design : 홈 캐러셀 글자 문구, 디자인 수정
  src/api/queries/categoryQueries.ts
  src/api/queries/userQueries.ts
  src/app/(default)/mypage/profile/ProfileClient.tsx
  src/app/(default)/mypage/profile/page.tsx
  src/components/HomePageClient.tsx
  src/components/RecommendedList.tsx
  src/components/SentenceComponent.tsx
Labels: 🌝 fe, ⚒️ refactor, 🌈design

#419 chore : 로그인 시 '로그인중..' 글자로 바꾸고 버튼 배경색 살짝 연해지도록 디자인 변경
  src/app/(fullscreen)/login/page.tsx
  src/components/common/LoadingSpinner.tsx
Labels: 🌝 fe, 🌈design, ⚙️ chore

#421 fix: 모바일 서치 input 안 보이는 버그 수정
  src/components/layout/Header.tsx
  src/components/layout/MobileSearch.tsx
Labels: 🌝 fe, 🐞 fix

#423 fix : ios mobile pb-20에 맞춰서 플로팅버튼 위치를 20px씩 올리기, fix : router.push를 router.replace로 변경하여 뒤로가기 불가능하도록 변경
  src/app/(default)/learn/listening/detail/ListeningDetailClient.tsx
  src/app/(default)/learn/reading/detail/ReadingDetailClient.tsx
  src/app/(default)/mypage/layout.tsx
  src/app/(fullscreen)/login/page.tsx
  src/app/not-found.tsx
Labels: 🌝 fe, 🐞 fix

#425 fix : tailwind문법 대신 bottom-[100px]로 static하게 지정해주기
  src/app/(default)/learn/listening/detail/ListeningDetailClient.tsx
  src/app/(default)/learn/reading/detail/ReadingDetailClient.tsx
  src/components/common/FloatingButtons.tsx
Labels: 🌝 fe, 🐞 fix, 🌈design

#429 fix : 기존 learningRate보다 작을 때만 learningRate업데이트를 하고 있던 문제 해결
  src/hooks/useUpdateLearningProgressOnUnmount.ts
Labels: 🌝 fe, 🐞 fix

#430 feat: 서치, 추천 콘텐츠 포인트 커버 추가
  src/api/hooks/usePoint.ts
  src/api/queries/pointQueries.ts
  src/app/(default)/search/page.tsx
  src/components/RecommendedList.tsx
  src/components/common/PointCover.tsx
Labels: 🌝 fe, 🐞 fix

#431 feat: 서치 컴포넌트에 배지 추가
  src/app/(default)/search/page.tsx
Labels: 🐞 fix, P3
